Marketplace/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('appMarketplace.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^freelancer/', include('freelancer.urls')),
    url(r'^employee/', include('employee.urls')),
    url(r'^aroundtheweb/', include('scraper.urls')),
    url(r'^details/', include('details.urls')),
    url(r'^message/', include('message.urls')),
]

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'

urlpatterns = [

    url(r'^login/$', views.login_view, name="login"),
#    url(r'^login/$', auth_views.login, {'template_name': 'accounts/login_form.html'}, name="login"),
#    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name="logout"),
    url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/login/'}, name="logout"),
    url(r'^employeesignup/$', views.SignUpViewE, name="e_reg"),
    url(r'^freelancersignup/$', views.SignUpViewF, name="f_reg"),
#    url(r'^freelancersignup/$', views.UserFormView.as_view(), name="f_reg"),

]

details/urls.py
from django.conf.urls import url
from . import views

app_name = 'details'

urlpatterns = [

    url(r'^job-details/(?P<job_id>[0-9]+)/$', views.job_details, name='job_details'),
    url(r'^job-details/edit-job/(?P<job_id>[0-9]+)/$', views.edit_job, name='edit_job'),
    #url(r'^$', views.job_details, name='job_details'),
    url(r'^job-details/edit-bid/(?P<bid_id>[0-9]+)/$', views.edit_bid, name='edit_bid'),

]

employee/urls.py
from django.conf.urls import url
from . import views

app_name = 'employee'

urlpatterns = [

    url(r'^$', views.e_home, name='e_home'),
    url(r'^add-job/$', views.add_job, name='add_job'),
#    url(r'^edit-job/$', views.edit_job, name='edit_job'),
    url(r'^profile/(?P<user_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^profile/edit-profile/(?P<user_id>[0-9]+)/$', views.edit_profile, name='edit_profile'),

]

freelancer/urls.py
from django.conf.urls import url
from . import views

app_name = 'freelancer'

urlpatterns = [

    url(r'^$', views.f_home, name='f_home'),
    url(r'^profile/(?P<user_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^profile/edit-profile/(?P<user_id>[0-9]+)/$', views.edit_profile, name='edit_profile'),


]

message/urls.py
from django.conf.urls import url
from . import views

app_name = 'message'

urlpatterns = [

    url(r'^list/(?P<user_id>[0-9]+)/$', views.message, name='message'),

]

scraper/urls.py
from django.conf.urls import url
from . import views

app_name = 'scraper'

urlpatterns = [
    url(r'^$', views.ScraperView, name = "aroundtheweb"),
]

scraper/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Job(models.Model):
    website = models.CharField(max_length=100)
    title = models.CharField(max_length=500)
    link = models.CharField(max_length=500)
    short_text = models.TextField()
    #job_type = models.CharField(max_length=50)
    time = models.CharField(max_length=50)
    skill = models.CharField(max_length=100)
    budget = models.CharField(max_length=50)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title # + ' --Posted On ' + self.website

scraper/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from accounts.models import ProfileEmp, ProfileFree
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Job
from message.models import Message
import requests
from bs4 import BeautifulSoup


# Create your views here.


def ScraperView(request):
    user = User.objects.all()
    name = request.user

    emp_all = ProfileEmp.objects.all()
    free_all = ProfileFree.objects.all()


    for emp in emp_all:
        if name == emp.user:
            emp_user = True
            break
        else:
            emp_user = False

    for free in free_all:
        if name == free.user:
            free_user = True
            break
        else:
            free_user = False

    all_messages = Message.objects.all()
    count_message_e = 0

    for message in all_messages:
        if name == message.post_user and message.viewed == False:
            count_message_e = count_message_e + 1



    all_jobs = Job.objects.all()

    url = "https://www.freelancer.com/jobs/regions/?keyword=web%20development#"
    r = requests.get(url)
    soup = BeautifulSoup(r.content, "lxml")

    # final product
    g_data = soup.find_all("div", {"class": "JobSearchCard-primary"})
    swebsite = 'freelancer.com'
    i = 0

    try:
        for item in g_data:
            if i == 5:
                break
            else:
                stitle = item.contents[1].find_all("a", {"class": "JobSearchCard-primary-heading-link"})[0].text
                slink = item.contents[1].find_all("a", {"class": "JobSearchCard-primary-heading-link"})[0].get("href")
                stime = item.contents[1].find_all("span", {"class": "JobSearchCard-primary-heading-Days"})[0].text
                sdescription = item.contents[3].text
                sskill = item.contents[5].text.replace('\n', '  ')
                sbudget = item.contents[7].text.replace('\n', ' ')


                for job in all_jobs:
                    if slink == job.link:
                        found = True
                        break
                    else:
                        found = False

                if not found :
                    #adding data to database
                    Job.objects.create(website=swebsite, title=stitle, link=slink, short_text=sdescription, time=stime, skill=sskill, budget=sbudget)
                else:
                    pass

            i+=1
    except:
        pass

    #calling all data from database
    all_jobs = Job.objects.all().order_by('-created_date')
    #all_jobs = Job.objects.filter('created_date')

    #pagination
    paginator = Paginator(all_jobs, 10) # Show 10 jobs per page
    page = request.GET.get('page')
    try:
        jobs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        jobs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        jobs = paginator.page(paginator.num_pages)


    context = {
        'all_jobs': all_jobs,
        'jobs': jobs,
        'name': name,
        'emp_user': emp_user,
        'free_user': free_user,
        'all_messages': all_messages,
        'count_message_e': count_message_e,
        
    }

    return render(request, 'scraper/ScraperView.html', context)

scraper/templates/scraper/ScraperView.html
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
      <title>GETWORK - Around The Web</title>
      {% load static %}
      <link rel="stylesheet" href="{% static 'scraper/css/style.css' %}" type='text/css'>
  </head>

  <body>
    <header>
      <div class="container">
        <div id="branding">
          <span class="highlight"><a href="/"><h1>GETWORK</h1></a></span>
        </div>
        <nav>
          {% if name.is_authenticated and emp_user == True and free_user == False %}
            <ul>
              <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
              <li><a href="{% url 'employee:e_home' %}">Browse Jobs</a></li>
              <li><a href="{% url 'employee:add_job' %}">Post a Job</a></li>
              <li><a href="{% url 'message:message' name.id %}">MESSAGES({{count_message_e}})</a></li>
              <li><a href="{% url 'employee:profile' name.id %}">{{ name.username }}</a></li>
              <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            </ul>
          {% elif name.is_authenticated and free_user == True and emp_user == False %}
            <ul>
              <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
              <li><a href="{% url 'freelancer:f_home' %}">Browse Jobs</a></li>
            <!--  <li><a href="{% url 'message:message' name.id %}">MESSAGES({{count_message_f}})</a></li>-->
              <li><a href="{% url 'freelancer:profile' name.id %}">{{ name.username }}</a></li>
              <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            </ul>
          {% else %}
            <ul>
              <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
              <li><a href="{% url 'accounts:e_reg' %}">Hire Freelancer</a></li>
              <li><a href="{% url 'accounts:f_reg' %}">Become A Freelancer</a></li>
              <li><a href="{% url 'accounts:login' %}">Login</a></li>
            </ul>
          {% endif %}
        </nav>
      </div>
    </header>

    <section id="newsletter">
      <div class="container">
        <h1>Subscribe To Our Newsletter</h1>
        <form>
          <input type="email" placeholder="Enter Email...">
          <button type="submit" class="button_1">Subscribe</button>
        </form>

      </div>
    </section>

    <section id="page_title">
      <h1>Jobs For Web developers Around The Web</h1>
    </section>

    <section id="main">
      <div class="container">
        <article id="main-col">
          <ul>

            {% for job in jobs %}
            <div class='card '>
              <a class="card-header" href="https://www.freelancer.com{{ job.link }}">
                <div class="card-title">
              <h2>"{{ job.title }}"</h2></a> <p>--{{ job.time }}</p></br>
                <p><b>Budget:</b> {{ job.budget }}</p></br><p><b>Description:</b> {{ job.short_text }}</p></br>
                <p><b>Skills:</b> {{ job.skill }}</p>
              </div>
              </div>
            {% endfor %}

            <!--pagination-->
            <div class="pagination">
              <span class="step-links">
                  {% if jobs.has_previous %}
                      <a href="?page={{ jobs.previous_page_number }}">previous</a>
                  {% endif %}

                  <span class="current">
                      Page {{ jobs.number }} of {{ jobs.paginator.num_pages }}.
                  </span>

                  {% if jobs.has_next %}
                      <a href="?page={{ jobs.next_page_number }}">next</a>
                  {% endif %}
              </span>
            </div>

          </ul>
        </article>
      </div>
    </section>


    <!--
    <section id="main">
      <div class="container">
        <article id="main-col">
          <ul>
            {% for job in all_jobs %}
            <li><a href="https://www.freelancer.com{{ job.link }}">
              <h2>"{{ job.title }}"</h2></a> <p>--{{ job.time }}</p></br>
                <p><b>Budget:</b> {{ job.budget }}</p></br><p><b>Description:</b> {{ job.short_text }}</p></br>
                <p><b>Skills:</b> {{ job.skill }}</p>
              </br></br><p>----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</p></br></br></li>
            {% endfor %}
          </ul>
        </article>
      </div>
    </section>
  -->
    <footer>
      <p>GETWORK.com, Copyright &copy; 2017</p>
    </footer>
  </body>
</html>