Marketplace/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('appMarketplace.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^freelancer/', include('freelancer.urls')),
    url(r'^employee/', include('employee.urls')),
    url(r'^aroundtheweb/', include('scraper.urls')),
    url(r'^details/', include('details.urls')),
    url(r'^message/', include('message.urls')),
]

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'

urlpatterns = [

    url(r'^login/$', views.login_view, name="login"),
#    url(r'^login/$', auth_views.login, {'template_name': 'accounts/login_form.html'}, name="login"),
#    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name="logout"),
    url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/login/'}, name="logout"),
    url(r'^employeesignup/$', views.SignUpViewE, name="e_reg"),
    url(r'^freelancersignup/$', views.SignUpViewF, name="f_reg"),
#    url(r'^freelancersignup/$', views.UserFormView.as_view(), name="f_reg"),

]

appMarketplace/urls.py
from django.conf.urls import url
from . import views

app_name = 'appMarketplace'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact_us, name='contact_us'),
]

details/urls.py
from django.conf.urls import url
from . import views

app_name = 'details'

urlpatterns = [

    url(r'^job-details/(?P<job_id>[0-9]+)/$', views.job_details, name='job_details'),
    url(r'^job-details/edit-job/(?P<job_id>[0-9]+)/$', views.edit_job, name='edit_job'),
    #url(r'^$', views.job_details, name='job_details'),
    url(r'^job-details/edit-bid/(?P<bid_id>[0-9]+)/$', views.edit_bid, name='edit_bid'),

]

employee/urls.py
from django.conf.urls import url
from . import views

app_name = 'employee'

urlpatterns = [

    url(r'^$', views.e_home, name='e_home'),
    url(r'^add-job/$', views.add_job, name='add_job'),
#    url(r'^edit-job/$', views.edit_job, name='edit_job'),
    url(r'^profile/(?P<user_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^profile/edit-profile/(?P<user_id>[0-9]+)/$', views.edit_profile, name='edit_profile'),

]

message/urls.py
from django.conf.urls import url
from . import views

app_name = 'message'

urlpatterns = [

    url(r'^list/(?P<user_id>[0-9]+)/$', views.message, name='message'),

]

scraper/urls.py
from django.conf.urls import url
from . import views

app_name = 'scraper'

urlpatterns = [
    url(r'^$', views.ScraperView, name = "aroundtheweb"),
]

appMarketplace/models.py
from django.db import models

# Create your models here.

appMarketplace/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from message.models import Message
from accounts.models import ProfileEmp, ProfileFree


# Create your views here.



def index(request):
    user = User.objects.all()
    name = request.user
    emp_all = ProfileEmp.objects.all()
    free_all = ProfileFree.objects.all()

    for emp in emp_all:
        if name == emp.user:
            emp_user = True
            break
        else:
            emp_user = False

    for free in free_all:
        if name == free.user:
            free_user = True
            break
        else:
            free_user = False

    all_messages = Message.objects.all()
    count_message_e = 0

    for message in all_messages:
        if name == message.post_user and message.viewed == False:
            count_message_e = count_message_e + 1


    context = {
        'emp_user': emp_user,
        'free_user': free_user,
        'name': name,
        'all_messages': all_messages,
        'count_message_e': count_message_e,

    }

    return render(request, 'appMarketplace/home.html', context)


def about(request):
    user = User.objects.all()
    name = request.user
    emp_all = ProfileEmp.objects.all()
    free_all = ProfileFree.objects.all()

    for emp in emp_all:
        if name == emp.user:
            emp_user = True
            break
        else:
            emp_user = False

    for free in free_all:
        if name == free.user:
            free_user = True
            break
        else:
            free_user = False

    all_messages = Message.objects.all()
    count_message_e = 0

    for message in all_messages:
        if name == message.post_user and message.viewed == False:
            count_message_e = count_message_e + 1


    context = {
        'emp_user': emp_user,
        'free_user': free_user,
        'name': name,
        'all_messages': all_messages,
        'count_message_e': count_message_e,

    }

    return render(request, 'appMarketplace/about.html', context)


def contact_us(request):
    user = User.objects.all()
    name = request.user
    emp_all = ProfileEmp.objects.all()
    free_all = ProfileFree.objects.all()

    for emp in emp_all:
        if name == emp.user:
            emp_user = True
            break
        else:
            emp_user = False

    for free in free_all:
        if name == free.user:
            free_user = True
            break
        else:
            free_user = False

    all_messages = Message.objects.all()
    count_message_e = 0

    for message in all_messages:
        if name == message.post_user and message.viewed == False:
            count_message_e = count_message_e + 1


    context = {
        'emp_user': emp_user,
        'free_user': free_user,
        'name': name,
        'all_messages': all_messages,
        'count_message_e': count_message_e,

    }

    return render(request, 'appMarketplace/contact_us.html', context)

appMarketplace/templates/appMarketplace/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>About | GETWORK</title>
    <link rel="stylesheet" href="../static/appMarketplace/css/style.css" type='text/css'>
  </head>


<body>
  <header>
    <div class="container">
      <div id="branding">
        <span class="highlight"><a href="/"><h1>GETWORK</h1></a></span>
      </div>
      <nav>
        {% if name.is_authenticated and emp_user == True and free_user == False %}
          <ul>
            <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
            <li><a href="{% url 'employee:e_home' %}">Browse Jobs</a></li>
            <li><a href="{% url 'employee:add_job' %}">Post a Job</a></li>
            <li><a href="{% url 'message:message' name.id %}">MESSAGES({{count_message_e}})</a></li>
            <li><a href="{% url 'employee:profile' name.id %}">{{ name.username }}</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          </ul>
        {% elif name.is_authenticated and free_user == True and emp_user == False %}
          <ul>
            <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
            <li><a href="{% url 'freelancer:f_home' %}">Browse Jobs</a></li>
          <!--  <li><a href="{% url 'message:message' name.id %}">MESSAGES({{count_message_f}})</a></li>-->
            <li><a href="{% url 'freelancer:profile' name.id %}">{{ name.username }}</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          </ul>
        {% else %}
          <ul>
            <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
            <li><a href="{% url 'accounts:e_reg' %}">Hire Freelancer</a></li>
            <li><a href="{% url 'accounts:f_reg' %}">Become A Freelancer</a></li>
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
          </ul>
        {% endif %}
      </nav>
    </div>
  </header>

  <section id="aboutshowcase">
    <div class="container">
      <h1>About Us</h1>
      <p>Creating a World Of Work Without Limits</p>
    </div>
  </section>


  <section id="newsletter">
    <div class="container">
      <h1>Subscribe To Our Newsletter</h1>
      <form>
        <input type="email" placeholder="Enter Email...">
        <button type="submit" class="button_1">Subscribe</button>
      </form>
    </div>
  </section>


  <section id="main">
    <div class="container">
      <article id="main-col">
        <p>
          <h3><b>Our story</b></h3>

          The GETWORK story begins over a decade ago, when the tech lead of a Silicon Valley startup realized his close friend in Athens would be perfect for a web project. The team agreed he was the best choice, but were concerned about working with someone halfway around the globe.

          <h3><b>A new way of working is born</b></h3>

          In response, the two friends created a new web-based platform that brought visibility and trust to remote work. It was so successful the two realized other businesses would also benefit from reliable access to a larger pool of quality talent, while workers would enjoy freedom and flexibility to find jobs online. Together they decided to start a company that would deliver on the promise of this technology.

          Fast-forward to today, that technology is the foundation of GETWORK — the world’s leading freelancing website. With millions of jobs posted on GETWORK annually, freelancers are earning more than $1 billion via the site each year and providing companies with over 3,500 skills.

          <h3><b>A world of opportunities</b></h3>

          Through GETWORK businesses get more done, connecting with freelancers to work on projects about web development, software development and mobile app developments. GETWORK makes it fast, simple, and cost-effective to find, hire, work with, and pay the best professionals anywhere, any time.

          <h3><b>GETWORK’s vision</b></h3>

          To connect businesses with great talent to work without limits.
        </p>
      </article>

      <aside id="sidebar">
        <div class="dark">
          <h3>Our Online Economy</h3>
          <p>
            The video below illustrates the Freelancer online economy. The pink lines indicate where projects are being posted by employers, and the blue lines indicate where the projects are being performed by freelancers. Thicker lines indicate a higher dollar volume of work. White dots indicate the location of Freelancer's users.
          </p>
        </div>
      </aside>
    </div>
  </section>

  <footer>
    <a  style="text-decoration-line: none; color:white;" href="{% url 'appMarketplace:index' %}">Home</a> - <a style="text-decoration-line: none; color:white;" href="{% url 'appMarketplace:contact_us' %}">Contact Us</a>
    <p>GETWORK.com, Copyright &copy; 2017</p>
  </footer>

</body>

</html>

appMarketplace/templates/appMarketplace/contact_us.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Contact Us</title>
		{% load static %}
		<link rel="stylesheet" href="{% static 'appMarketplace/css/contact_us_style.css' %}" type="text/css">
	</head>

	<body>
		<header>
	    <div class="container">
	      <div id="branding">
	        <span class="highlight"><a href="/"><h1>GETWORK</h1></a></span>
	      </div>
	      <nav>
					{% if name.is_authenticated and emp_user == True and free_user == False %}
	          <ul>
	            <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
	            <li><a href="{% url 'employee:e_home' %}">Browse Jobs</a></li>
	            <li><a href="{% url 'employee:add_job' %}">Post a Job</a></li>
							<li><a href="{% url 'message:message' name.id %}">MESSAGES({{count_message_e}})</a></li>
							<li><a href="{% url 'employee:profile' name.id %}">{{ name.username }}</a></li>
	            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
	          </ul>
	        {% elif name.is_authenticated and free_user == True and emp_user == False %}
	          <ul>
	            <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
							<li><a href="{% url 'freelancer:f_home' %}">Browse Jobs</a></li>
					<!--		<li><a href="{% url 'message:message' name.id %}">MESSAGES({{count_message_f}})</a></li>-->
							<li><a href="{% url 'freelancer:profile' name.id %}">{{ name.username }}</a></li>
	            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
	          </ul>
	        {% else %}
	          <ul>
	            <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
	            <li><a href="{% url 'accounts:e_reg' %}">Hire Freelancer</a></li>
	            <li><a href="{% url 'accounts:f_reg' %}">Become A Freelancer</a></li>
	            <li><a href="{% url 'accounts:login' %}">Login</a></li>
	          </ul>
	        {% endif %}
	      </nav>
	    </div>
	  </header>

		<div class="container">
		  <form id="contact" action="" method="post">
		    <h3>Quick Contact</h3>
		    <h4>Contact us today, and get reply with in 24 hours!</h4>
		    <fieldset>
		      <input placeholder="Your name" type="text" tabindex="1" required autofocus>
		    </fieldset>
		    <fieldset>
		      <input placeholder="Your Email Address" type="email" tabindex="2" required>
		    </fieldset>
		    <fieldset>
		      <input placeholder="Your Phone Number" type="tel" tabindex="3" required>
		    </fieldset>
		    <fieldset>
		      <input placeholder="Your Web Site starts with http://" type="url" tabindex="4" required>
		    </fieldset>
		    <fieldset>
		      <textarea placeholder="Type your Message Here...." tabindex="5" required></textarea>
		    </fieldset>
		    <fieldset>
		      <button name="submit" type="submit" id="contact-submit" data-submit="...Sending">Submit</button>
		    </fieldset>
		  </form>


		</div>

	</body>
</html>

appMarketplace/templates/appMarketplace/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>GETWORK - Hire Programmers For Your Development</title>
    <link rel="stylesheet" href="static/appMarketplace/css/style.css" type='text/css'>

  </head>


<body>
  <header>
    <div class="container">
      <div id="branding">
        <span class="highlight"><a href="/"><h1>GETWORK</h1></a></span>
      </div>
      <nav>
        {% if name.is_authenticated and emp_user == True and free_user == False %}
          <ul>
            <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
            <li><a href="{% url 'employee:e_home' %}">Browse Jobs</a></li>
            <li><a href="{% url 'employee:add_job' %}">Post a Job</a></li>
            <li><a href="{% url 'message:message' name.id %}">MESSAGES({{count_message_e}})</a></li>
            <li><a href="{% url 'employee:profile' name.id %}">{{ name.username }}</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          </ul>
        {% elif name.is_authenticated and free_user == True and emp_user == False %}
          <ul>
            <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
            <li><a href="{% url 'freelancer:f_home' %}">Browse Jobs</a></li>
          <!--  <li><a href="{% url 'message:message' name.id %}">MESSAGES({{count_message_f}})</a></li>-->
            <li><a href="{% url 'freelancer:profile' name.id %}">{{ name.username }}</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          </ul>
        {% else %}
          <ul>
            <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
            <li><a href="{% url 'accounts:e_reg' %}">Hire Freelancer</a></li>
            <li><a href="{% url 'accounts:f_reg' %}">Become A Freelancer</a></li>
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
          </ul>
        {% endif %}
      </nav>
    </div>
  </header>

  <section id="showcase">
    <style>
      #showcase{
        background: url("static/appMarketplace/img/showcase.jpg") no-repeat 0 -400px;
      }
    </style>
    <div class="container">
      <h1>Get More Done With The Freelancers</h1>
      <p>Millions of small businesses use freelance jobs to turn their ideas into reality</p>
    </div>
  </section>

  <section id="newsletter">
    <div class="container">
      <h1>Subscribe To Our Newsletter</h1>
      <form>
        <input type="email" placeholder="Enter Email...">
        <button type="submit" class="button_1">Subscribe</button>
      </form>
    </div>
  </section>


  <section id="boxes">
    <div class="container">
      <div class="box">
        <img src="static/appMarketplace/img/logo_html.png">
        <h3>HTML5 Markups</h3>
        <p>Various Jobs about HTML5. Help someone to create their first website.</p>
      </div>
      <div class="box">
        <img src="static/appMarketplace/img/logo_css.png">
        <h3>CSS3 Styling</h3>
        <p>Various Jobs about CSS3. Help someone to style their website.</p>
      </div>
      <div class="box">
        <img src="static/appMarketplace/img/logo_brush.png">
        <h3>Graphics Design</h3>
        <p>Various Jobs about Graphics Design. Help someone to create Design Their world.</p>
      </div>
    </div>
  </section>

  <footer id="foot">
    <a  style="text-decoration-line: none; color:white;" href="{% url 'appMarketplace:about' %}">About Us</a> - <a style="text-decoration-line: none; color:white;" href="{% url 'appMarketplace:contact_us' %}">Contact Us</a>
    <p>GETWORK.com, Copyright &copy; 2017</p>
  </footer>

</body>

</html>