Marketplace/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('appMarketplace.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^freelancer/', include('freelancer.urls')),
    url(r'^employee/', include('employee.urls')),
    url(r'^aroundtheweb/', include('scraper.urls')),
    url(r'^details/', include('details.urls')),
    url(r'^message/', include('message.urls')),
]

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'

urlpatterns = [

    url(r'^login/$', views.login_view, name="login"),
#    url(r'^login/$', auth_views.login, {'template_name': 'accounts/login_form.html'}, name="login"),
#    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name="logout"),
    url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/login/'}, name="logout"),
    url(r'^employeesignup/$', views.SignUpViewE, name="e_reg"),
    url(r'^freelancersignup/$', views.SignUpViewF, name="f_reg"),
#    url(r'^freelancersignup/$', views.UserFormView.as_view(), name="f_reg"),

]

details/urls.py
from django.conf.urls import url
from . import views

app_name = 'details'

urlpatterns = [

    url(r'^job-details/(?P<job_id>[0-9]+)/$', views.job_details, name='job_details'),
    url(r'^job-details/edit-job/(?P<job_id>[0-9]+)/$', views.edit_job, name='edit_job'),
    #url(r'^$', views.job_details, name='job_details'),
    url(r'^job-details/edit-bid/(?P<bid_id>[0-9]+)/$', views.edit_bid, name='edit_bid'),

]

employee/urls.py
from django.conf.urls import url
from . import views

app_name = 'employee'

urlpatterns = [

    url(r'^$', views.e_home, name='e_home'),
    url(r'^add-job/$', views.add_job, name='add_job'),
#    url(r'^edit-job/$', views.edit_job, name='edit_job'),
    url(r'^profile/(?P<user_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^profile/edit-profile/(?P<user_id>[0-9]+)/$', views.edit_profile, name='edit_profile'),

]

freelancer/urls.py
from django.conf.urls import url
from . import views

app_name = 'freelancer'

urlpatterns = [

    url(r'^$', views.f_home, name='f_home'),
    url(r'^profile/(?P<user_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^profile/edit-profile/(?P<user_id>[0-9]+)/$', views.edit_profile, name='edit_profile'),


]

message/urls.py
from django.conf.urls import url
from . import views

app_name = 'message'

urlpatterns = [

    url(r'^list/(?P<user_id>[0-9]+)/$', views.message, name='message'),

]

scraper/urls.py
from django.conf.urls import url
from . import views

app_name = 'scraper'

urlpatterns = [
    url(r'^$', views.ScraperView, name = "aroundtheweb"),
]

freelancer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from employee.models import This_Job

# Create your models here.


class Bid(models.Model):
    job = models.ForeignKey(This_Job, default=1, on_delete=models.CASCADE, related_name='bids')
    bid_poster = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    bid_text = models.TextField()
    bid_time = models.CharField(max_length=50)
    bid_budget = models.CharField(max_length=50)
    bid_posted_time = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.job.title

freelancer/forms.py
from django import forms
from .models import Bid

# Create your forms here.


class Bid_Form(forms.ModelForm):

    class Meta:
        model = Bid
        fields = ['bid_text', 'bid_time', 'bid_budget']

freelancer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from accounts.models import ProfileEmp, ProfileFree
from employee.models import This_Job
from freelancer.models import Bid
from message.models import Message
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.


@login_required
def f_home(request):
    user = User.objects.all()
    name = request.user
    free_all = ProfileFree.objects.all()

    for free in free_all:
        if name == free.user:
            this_user = True
            break
        else:
            this_user = False

    all_jobs = This_Job.objects.all().order_by('-created_date')

    #pagination
    paginator = Paginator(all_jobs, 5) # Show 10 jobs per page
    page = request.GET.get('page')
    try:
        jobs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        jobs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        jobs = paginator.page(paginator.num_pages)

    all_messages = Message.objects.all()
    count_message_e = 0

    for message in all_messages:
        if name == message.post_user and message.viewed == False:
            count_message_e = count_message_e + 1


    context = {
        'name': name,
        'this_user': this_user,
        'all_jobs': all_jobs,
        'jobs': jobs,
        'all_messages': all_messages,
        'count_message_e': count_message_e,

    }

    return render(request, 'freelancer/f_home.html', context)


@login_required
def profile(request, user_id):
    profile = get_object_or_404(User, pk=user_id)
    profile_free = ProfileFree.objects.get(user=profile)
    user = User.objects.all()
    name = request.user

    free_all = ProfileFree.objects.all()
    emp_all = ProfileEmp.objects.all()

    for emp in emp_all:
        if name == emp.user:
            emp_user = True
            break
        else:
            emp_user = False

    for free in free_all:
        if name == free.user:
            free_user = True
            break
        else:
            free_user = False


    all_jobs = This_Job.objects.all()
    all_bids = Bid.objects.all()

    all_messages = Message.objects.all()
    count_message_e = 0

    for message in all_messages:
        if name == message.post_user and message.viewed == False:
            count_message_e = count_message_e + 1


    context = {
        'name': name,
        'user': user,
        'free_user': free_user,
        'emp_user': emp_user,
        'emp_all': emp_all,
        'profile': profile,
        'profile_free': profile_free,
        'all_jobs': all_jobs,
        'all_bids': all_bids,
        'all_messages': all_messages,
        'count_message_e': count_message_e,

    }
    return render(request, 'freelancer/profile.html', context)


@login_required
def edit_profile(request, user_id):
    profile = get_object_or_404(User, pk=user_id)
    profile_free = ProfileFree.objects.get(user=profile)
    user = User.objects.all()
    name = request.user

    free_all = ProfileFree.objects.all()
    emp_all = ProfileEmp.objects.all()

    for emp in emp_all:
        if name == emp.user:
            emp_user = True
            break
        else:
            emp_user = False

    for free in free_all:
        if name == free.user:
            free_user = True
            break
        else:
            free_user = False

    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        portfolio = request.POST['portfolio']
        address1 = request.POST['address1']
        address2 = request.POST['address2']
        city = request.POST['city']
        country = request.POST['country']
        about = request.POST['about']

        profile.first_name = first_name
        profile.last_name = last_name
        profile_free.portfolio = portfolio
        profile_free.address1 = address1
        profile_free.address2 = address2
        profile_free.city = city
        profile_free.country = country
        profile_free.about = about

        profile.save()
        profile_free.save()

        return redirect('freelancer:profile', profile.id)

    all_messages = Message.objects.all()
    count_message_e = 0

    for message in all_messages:
        if name == message.post_user and message.viewed == False:
            count_message_e = count_message_e + 1


    context = {
        'profile': profile,
        'profile_free': profile_free,
        'name': name,
        'user': user,
        'free_user': free_user,
        'emp_user': emp_user,
        'all_messages': all_messages,
        'count_message_e': count_message_e,

    }
    return render(request, 'freelancer/edit_profile.html', context)

freelancer/templates/freelancer/base_freelancer.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <title>{% block title %}GETWORK{% endblock %}</title>


    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'freelancer/css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'employee/css/contact_us_style.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>


  <body>

    {% if this_user %}

      <header>
        <div class="container">
          <div id="branding">
            <span class="highlight"><a href="/"><h1>GETWORK</h1></a></span>
          </div>
          <nav>
              <ul>
                <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
                <li><a href="{% url 'freelancer:f_home' %}">Browse Jobs</a></li>
            <!--    <li><a href="{% url 'message:message' name.id %}">MESSAGES({{count_message_f}})</a></li>-->
                <li><a href="{% url 'freelancer:profile' name.id %}">{{ name.username }}</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
              </ul>
          </nav>
        </div>
      </header>

      <section id="aboutshowcase">
        <div class="container">
          <h1>Show Everyone What You Can Do</h1>
        </div>
      </section>

      {% block body %}
      {% endblock %}

      <!--<div id="container">
        <div id="main">

        </div>
      </div>-->

      <footer id="foot">
        <a style="text-decoration-line: none; color:white;" href="{% url 'appMarketplace:index' %}">Home</a> - <a  style="text-decoration-line: none; color:white;" href="{% url 'appMarketplace:about' %}">About Us</a> - <a style="text-decoration-line: none; color:white;" href="{% url 'appMarketplace:contact_us' %}">Contact Us</a>
        <p>GETWORK.com, Copyright &copy; 2017</p>
      </footer>

    {% else %}

      <header>
        <div class="container">
          <div id="branding">
            <span class="highlight"><a href="/"><h1>GETWORK</h1></a></span>
          </div>
          <nav>
            <ul>
              <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            </ul>
          </nav>
        </div>
      </header>

      <div style="text-align: center; margin-top: 50px;">
        <h1>Oops! You're Not Allowed To See This Page!<br>
          <a style="margin-top: 50px;" href="{% url 'appMarketplace:index' %}">GO HOME</a>
        </h1>
    </div>

    {% endif %}

  </body>

</html>

freelancer/templates/freelancer/base_profile.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <title>{% block title %}GETWORK{% endblock %}</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'freelancer/css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'employee/css/contact_us_style.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>


  <body>

      <header>
        <div class="container">
          <div id="branding">
            <span class="highlight"><a href="/"><h1>GETWORK</h1></a></span>
          </div>
          <nav>
            {% if name.is_authenticated and emp_user == True and free_user == False %}
              <ul>
                <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
                <li><a href="{% url 'employee:e_home' %}">Browse Jobs</a></li>
                <li><a href="{% url 'employee:add_job' %}">Post a Job</a></li>
                <li><a href="{% url 'message:message' name.id %}">MESSAGES({{count_message_e}})</a></li>
                <li><a href="{% url 'employee:profile' name.id %}">{{ name.username }}</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
              </ul>
            {% elif name.is_authenticated and free_user == True and emp_user == False %}
              <ul>
                <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
                <li><a href="{% url 'freelancer:f_home' %}">Browse Jobs</a></li>
              <!--  <li><a href="{% url 'message:message' name.id %}">MESSAGES({{count_message_f}})</a></li>-->
                <li><a href="{% url 'freelancer:profile' name.id %}">{{ name.username }}</a></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
              </ul>
            {% endif %}
          </nav>
        </div>
      </header>



      {% block body %}
      {% endblock %}

      <div id="container">
        <div id="main">

        </div>
      </div>

      <footer id="foot">
        <a style="text-decoration-line: none; color:white;" href="{% url 'appMarketplace:index' %}">Home</a> - <a  style="text-decoration-line: none; color:white;" href="{% url 'appMarketplace:about' %}">About Us</a> - <a style="text-decoration-line: none; color:white;" href="{% url 'appMarketplace:contact_us' %}">Contact Us</a>
        <p>GETWORK.com, Copyright &copy; 2017</p>
      </footer>

  </body>
</html>

freelancer/templates/freelancer/edit_profile.html
{% extends 'freelancer/base_profile.html' %}

{% block title %}{{ profile.username }} Profile - Edit{% endblock %}


{% block body %}


<div class="container">
  <form id="contact" method="POST" action="{% url 'freelancer:edit_profile' profile.id %}">
    {% csrf_token %}
    <h1>Edit Profile</h1>

    <fieldset>
      <input placeholder="First Name" name="first_name" type="text" tabindex="1" required autofocus>
    </fieldset>

    <fieldset>
      <input placeholder="Last Name" name="last_name" type="text" tabindex="2" required>
    </fieldset>

    <fieldset>
      <input placeholder="Portfolio Link" name="portfolio" type="text" tabindex="3" required>
    </fieldset>
    <fieldset>
      <input placeholder="Address Line 1" name="address1" type="text" tabindex="4" required>
    </fieldset>
    <fieldset>
      <input placeholder="Address Line 2" name="address2" type="text" tabindex="5" required>
    </fieldset>
    <fieldset>
      <input placeholder="City" name="city" type="text" tabindex="6" required>
    </fieldset>
    <fieldset>
      <input placeholder="Country" name="country" type="text" tabindex="7" required>
    </fieldset>
    <fieldset>
      <textarea placeholder="About You" name="about" tabindex="8" required></textarea>
    </fieldset>


    <fieldset>
      <button name="submit" type="submit" id="contact-submit" data-submit="...Posting">Re-Submit</button>
    </fieldset>
  </form>
</div>

{% endblock %}

freelancer/templates/freelancer/f_home.html
{% extends 'freelancer/base_freelancer.html' %}

{% block title %}GETWORK - Home{% endblock %}

{% block body %}

<div class="box-border">
  <section id="main">
    <article id="main-col">
      <ul>
        {% for job in jobs %}
          <div class="card">
            <div class="card-body">
              <p style="float:right; margin:10px;"><b>Budget: </b>{{ job.budget }}</p>
              <p><h2 class="card-title"><a href="{% url 'details:job_details' job.id %}">{{ job.title }}</a></h2> posted by: {{ job.user }}</p>

              {% if name.is_authenticated and name == job.user %}
                <a href="{% url 'details:edit_job' job.id %}" class="btn btn-primary" style="margin-bottom:5px;">Edit Job</a>
              {% endif %}

              <p><b>Job Duration:</b>  {{ job.time }}<p>
              <p><b>Description:</b> {{ job.short_text }}</p>
              <a href="{% url 'details:job_details' job.id %}" class="btn btn-primary" style="float:right;">Bid This Job</a>
              <p style="margin-top:5px;"><b>Skills:</b> {{ job.skill }}</p>
              <p><b>Posted On:</b>  {{ job.created_date }}<p>

            </div>
          </div>
        {% endfor %}

        <!--pagination-->
        <div class="pagination">
          <span class="step-links">
              {% if jobs.has_previous %}
                  <a href="?page={{ jobs.previous_page_number }}">previous</a>
              {% endif %}

              <span class="current">
                  Page {{ jobs.number }} of {{ jobs.paginator.num_pages }}.
              </span>

              {% if jobs.has_next %}
                  <a href="?page={{ jobs.next_page_number }}">next</a>
              {% endif %}
          </span>
        </div>

      </ul>
    </article>
  </section>
</div>


{% endblock %}

freelancer/templates/freelancer/profile.html
{% extends 'freelancer/base_profile.html' %}

{% block title %}{{ profile.username }} Profile{% endblock %}

{% block body %}

<ul class="nav nav-pills nav-justified">
  <li class="active"><a data-toggle="tab" href="#profile">MY ACCOUNT</a></li>
  <li><a data-toggle="tab" href="#bids">MY BIDS</a></li>
</ul>

<div class="tab-content">

  <!--tab 1 : profile -->
  <div id="profile" class="tab-pane fade in active">
    <div class="container">
      <div id="contact">

        <h2 style="margin-left:50px; margin-right:50px;"><b>First Name: </b>{{ profile.first_name }}</h2>
        <h2 style="margin-left:50px; margin-right:50px;"><b>Last Name: </b>{{ profile.last_name }}</h2>
        <h2 style="margin-left:50px; margin-right:50px;"><b>Username: </b>{{ profile.username }}</h2>
        <h2 style="margin-left:50px; margin-right:50px;"><b>Email Address: </b>{{ profile.email }}</h2>
        <h2 style="margin-left:50px; margin-right:50px;"><b>Portfolio: </b>{{ profile_free.portfolio }}</h2>
        <h2 style="margin-left:50px; margin-right:50px;"><b>Street Address: </b>{{ profile_free.address1 }}, {{ profile_free.address2 }}</h2>
        <h2 style="margin-left:50px; margin-right:50px;"><b>City: </b>{{ profile_free.city }}</h2>
        <h2 style="margin-left:50px; margin-right:50px;"><b>Country: </b>{{ profile_free.country }}</h2>
        <h2 style="margin-left:50px; margin-right:50px;"><b>About Me: </b>{{ profile_free.about }}</h2>

        {% if name.is_authenticated and name == profile %}
          <a style="margin-left:50px; margin-right:50px;" href="{% url 'freelancer:edit_profile' profile.id %}" class="btn btn-primary" style="margin-bottom:5px;">Edit Profile</a>
        {% endif %}

      </div>
    </div>
  </div>

  <!--tab 1 : bids -->
  <div id="bids" class="tab-pane fade">
    <div class="box-border">
      <section id="main">
        <article id="main-col">
          <ul>
            {% for bid in all_bids %}
              {% if profile == bid.bid_poster %}
                <div class="card">
                  <div class="card-body">
                    <h2><a href="{% url 'details:job_details' bid.job.id %}">{{ bid.job.title }}</a></h2>

                    {% if name == bid.bid_poster %}
                      <h3><b>Your Bid:</b></h3>
                    {% else %}
                      <h3><b>Bid:</b></h3>
                    {% endif %}

                    <p><b>Bid Description:</b> {{ bid.bid_text }}</p>
                    <p><b>Budget Needed: </b>{{ bid.bid_budget }}</p>
                    <p><b>Time Needed:</b>  {{ bid.bid_time }}<p>

                    {% if name.is_authenticated and name == bid.bid_poster %}
                      <a href="{% url 'details:edit_bid' bid.id %}" class="btn btn-primary" style="float:right;">Edit Bid</a>
                    {% endif %}

                    <p><b>Posted On:</b>  {{ bid.bid_posted_time }}<p>
                  </div>
                </div>
              {% endif %}
            {% endfor %}
          </ul>
        </article>
      </section>
    </div>
  </div>

</div>


{% endblock %}