Marketplace/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('appMarketplace.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^freelancer/', include('freelancer.urls')),
    url(r'^employee/', include('employee.urls')),
    url(r'^aroundtheweb/', include('scraper.urls')),
    url(r'^details/', include('details.urls')),
    url(r'^message/', include('message.urls')),
]

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'

urlpatterns = [

    url(r'^login/$', views.login_view, name="login"),
#    url(r'^login/$', auth_views.login, {'template_name': 'accounts/login_form.html'}, name="login"),
#    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name="logout"),
    url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/login/'}, name="logout"),
    url(r'^employeesignup/$', views.SignUpViewE, name="e_reg"),
    url(r'^freelancersignup/$', views.SignUpViewF, name="f_reg"),
#    url(r'^freelancersignup/$', views.UserFormView.as_view(), name="f_reg"),

]

details/urls.py
from django.conf.urls import url
from . import views

app_name = 'details'

urlpatterns = [

    url(r'^job-details/(?P<job_id>[0-9]+)/$', views.job_details, name='job_details'),
    url(r'^job-details/edit-job/(?P<job_id>[0-9]+)/$', views.edit_job, name='edit_job'),
    #url(r'^$', views.job_details, name='job_details'),
    url(r'^job-details/edit-bid/(?P<bid_id>[0-9]+)/$', views.edit_bid, name='edit_bid'),

]

employee/urls.py
from django.conf.urls import url
from . import views

app_name = 'employee'

urlpatterns = [

    url(r'^$', views.e_home, name='e_home'),
    url(r'^add-job/$', views.add_job, name='add_job'),
#    url(r'^edit-job/$', views.edit_job, name='edit_job'),
    url(r'^profile/(?P<user_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^profile/edit-profile/(?P<user_id>[0-9]+)/$', views.edit_profile, name='edit_profile'),

]

message/urls.py
from django.conf.urls import url
from . import views

app_name = 'message'

urlpatterns = [

    url(r'^list/(?P<user_id>[0-9]+)/$', views.message, name='message'),

]

scraper/urls.py
from django.conf.urls import url
from . import views

app_name = 'scraper'

urlpatterns = [
    url(r'^$', views.ScraperView, name = "aroundtheweb"),
]

details/models.py
from django.db import models

# Create your models here.

details/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from employee.models import This_Job
from freelancer.models import Bid
from message.models import Message
from django.contrib.auth.models import User
from accounts.models import ProfileEmp, ProfileFree
from freelancer.forms import Bid_Form
from employee.forms import Add_Job_Form

# Create your views here.

@login_required
def job_details(request, job_id):
    job = get_object_or_404(This_Job, pk=job_id)
    user = User.objects.all()
    name = request.user

    all_bids = Bid.objects.all()

    emp_all = ProfileEmp.objects.all()
    free_all = ProfileFree.objects.all()


    for emp in emp_all:
        if name == emp.user:
            emp_user = True
            break
        else:
            emp_user = False

    for free in free_all:
        if name == free.user:
            free_user = True
            break
        else:
            free_user = False


    #submit bid form
    if request.method == 'POST':
        form = Bid_Form(request.POST)
        if form.is_valid():
            bid = form.save(commit=False)
            bid.bid_poster = name
            bid.job = job
            bid.save()

            Message.objects.create(post_user=job.user, comment_user=name, job=job)

            #return redirect('details:job_details')
            return HttpResponseRedirect(request.path_info)
    else:
        form = Bid_Form()


    count_bid = 0

    for bid in all_bids:
        if job == bid.job:
            count_bid = count_bid+1

    for bid in all_bids:
        if job == bid.job and name == bid.bid_poster:
            bid_limit = True
            break
        else:
            bid_limit = False

    all_messages = Message.objects.all()
    count_message_e = 0

    for message in all_messages:
        if name == message.post_user and message.viewed == False:
            count_message_e = count_message_e + 1


    context = {
        'form': form,
        'user': user,
        'job': job,
        'name': name,
        'all_bids': all_bids,
        'count_bid': count_bid,
        'bid_limit': bid_limit,
        'emp_user': emp_user,
        'free_user': free_user,
        'all_messages': all_messages,
        'count_message_e': count_message_e,

    }
    return render(request, 'details/job_details.html', context)


@login_required
def edit_job(request, job_id):
    job = get_object_or_404(This_Job, pk=job_id)

    user = User.objects.all()
    name = request.user

    all_jobs = This_Job.objects.all()

    if request.method == 'POST':

        title = request.POST['title']
        short_text = request.POST['short_text']
        time = request.POST['time']
        skill = request.POST['skill']
        budget = request.POST['budget']

        job.title = title
        job.short_text = short_text
        job.time = time
        job.skill = skill
        job.budget = budget
        job.user = name
        job.save()
        return redirect('details:job_details', job.id)
        #return HttpResponseRedirect(request.path_info)

    else:
        form = Add_Job_Form()



    emp_all = ProfileEmp.objects.all()
    free_all = ProfileFree.objects.all()

    for emp in emp_all:
        if name == emp.user:
            emp_user = True
            break
        else:
            emp_user = False

    for free in free_all:
        if name == free.user:
            free_user = True
            break
        else:
            free_user = False

    all_messages = Message.objects.all()
    count_message_e = 0

    for message in all_messages:
        if name == message.post_user and message.viewed == False:
            count_message_e = count_message_e + 1


    context = {
        'user': user,
        'name': name,
        'all_jobs': all_jobs,
        'job': job,
        'free_user': free_user,
        'emp_user': emp_user,
        'all_messages': all_messages,
        'count_message_e': count_message_e,

    }
    return render(request, 'details/edit_job.html', context)



@login_required
def edit_bid(request, bid_id):
    bid = get_object_or_404(Bid, pk=bid_id)

    user = User.objects.all()
    name = request.user

    job = bid.job
    #submit bid form
    if request.method == 'POST':

        bid_text = request.POST['bid_text']
        bid_time = request.POST['bid_time']
        bid_budget = request.POST['bid_budget']

        bid.bid_text = bid_text
        bid.bid_time = bid_time
        bid.bid_budget = bid_budget
        bid.bid_poster = name
        bid.job = job
        bid.save()
        return redirect('details:job_details', job.id)
        #return HttpResponseRedirect(request.path_info)

    else:
        form = Bid_Form()



    emp_all = ProfileEmp.objects.all()
    free_all = ProfileFree.objects.all()


    for emp in emp_all:
        if name == emp.user:
            emp_user = True
            break
        else:
            emp_user = False

    for free in free_all:
        if name == free.user:
            free_user = True
            break
        else:
            free_user = False

    all_messages = Message.objects.all()
    count_message_e = 0

    for message in all_messages:
        if name == message.post_user and message.viewed == False:
            count_message_e = count_message_e + 1


    context = {
        'name': name,
        'free_user': free_user,
        'emp_user': emp_user,
        'bid': bid,
        'job': job,
        'all_messages': all_messages,
        'count_message_e': count_message_e,
        
    }
    return render(request, 'details/edit_bid.html', context)

details/templates/details/base_details.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <title>{% block title %}GETWORK{% endblock %}</title>


    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'employee/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'details/css/contact_us_style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

  </head>


  <body>

        <header>
          <div class="container">
            <div id="branding">
              <span class="highlight"><a href="/"><h1>GETWORK</h1></a></span>
            </div>
            <nav>
              {% if name.is_authenticated and emp_user == True and free_user == False %}
                <ul>
                  <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
                  <li><a href="{% url 'employee:e_home' %}">Browse Jobs</a></li>
                  <li><a href="{% url 'employee:add_job' %}">Post a Job</a></li>
                  <li><a href="{% url 'message:message' name.id %}">MESSAGES({{count_message_e}})</a></li>
                  <li><a href="{% url 'employee:profile' name.id %}">{{ name.username }}</a></li>
                  <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                </ul>
              {% elif name.is_authenticated and free_user == True and emp_user == False %}
                <ul>
                  <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
                  <li><a href="{% url 'freelancer:f_home' %}">Browse Jobs</a></li>
                <!--  <li><a href="{% url 'message:message' name.id %}">MESSAGES({{count_message_f}})</a></li>-->
                  <li><a href="{% url 'freelancer:profile' name.id %}">{{ name.username }}</a></li>
                  <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                </ul>
              {% else %}
                <ul>
                  <li><a href="{% url 'scraper:aroundtheweb' %}">Around The Web</a></li>
                  <li><a href="{% url 'accounts:e_reg' %}">Hire Freelancer</a></li>
                  <li><a href="{% url 'accounts:f_reg' %}">Become A Freelancer</a></li>
                  <li><a href="{% url 'accounts:login' %}">Login</a></li>
                </ul>
              {% endif %}
            </nav>
          </div>
        </header>

        <section id="aboutshowcase">
          <div class="container">
            <h1>{{ job.title }}</h1>
          </div>
        </section>




        {% block body %}
        {% endblock %}

        <!--keeping the footer at the footer-->
        <!--<div id="container">
          <div id="main">

          </div>
        </div>-->

        <footer style="margin-top:30px;" id="foot">
          <a style="text-decoration-line: none; color:white;" href="{% url 'appMarketplace:index' %}">Home</a> - <a  style="text-decoration-line: none; color:white;" href="{% url 'appMarketplace:about' %}">About Us</a> - <a style="text-decoration-line: none; color:white;" href="{% url 'appMarketplace:contact_us' %}">Contact Us</a>
          <p>GETWORK.com, Copyright &copy; 2017</p>
        </footer>
  </body>
</html>

details/templates/details/edit_bid.html
{% extends 'details/base_details.html' %}

{% block title %}Edit Bid : {{ bid.bid_poster }}{% endblock %}

{% block body %}

{% if name == bid.bid_poster %}
  <div class="container">
    <form id="contact" method="POST" action="{% url 'details:edit_bid' bid.id %}">
      {% csrf_token %}
      <h3>Edit Your Bid</h3>
      <fieldset>
        <textarea placeholder="Write Your Bid" name="bid_text" tabindex="1" required></textarea>
      </fieldset>
      <fieldset>
        <input placeholder="Time You Need (ex- 5 days)" name="bid_time" type="text" tabindex="2" required>
      </fieldset>
      <fieldset>
        <input placeholder="Budget You Need (ex- 100 dollars)" name="bid_budget" type="text" tabindex="3" required>
      </fieldset>
      <fieldset>
        <button name="submit" type="submit" id="contact-submit" data-submit="...Posting">Re-Submit</button>
      </fieldset>
    </form>
  </div>
{% else %}
  <div style="text-align: center; margin-top: 50px;">
    <h1>Oops! You're Not Allowed To See This Page!<br>
      <a style="margin-top: 50px;" href="{% url 'appMarketplace:index' %}">GO HOME</a>
    </h1>
  </div>
{% endif %}


{% endblock %}

details/templates/details/edit_job.html
{% extends 'details/base_details.html' %}

{% block title %}Edit Job : {{ job.title }}{% endblock %}

{% block body %}

{% if name == job.user %}
  <div class="container">
    <form id="contact" method="POST" action="{% url 'details:edit_job' job.id %}">
      {% csrf_token %}
      <h3>Edit The Job</h3>
      <fieldset>
        <input placeholder="Job Title" name="title" type="text" tabindex="1" required autofocus>
      </fieldset>
      <fieldset>
        <textarea placeholder="Job Description" name="short_text" tabindex="2" required></textarea>
      </fieldset>
      <fieldset>
        <input placeholder="Job Duration (ex- 5 days)" name="time" type="text" tabindex="3" required>
      </fieldset>
      <fieldset>
        <input placeholder="Specific Skills (ex- django, flask)" name="skill" type="text" tabindex="4" required>
      </fieldset>
      <fieldset>
        <input placeholder="Your Budget (ex- 100 dollars)" name="budget" type="text" tabindex="5" required>
      </fieldset>
      <fieldset>
        <button name="submit" type="submit" id="contact-submit" data-submit="...Posting">Re-Submit</button>
      </fieldset>
    </form>
  </div>
{% else %}
  <div style="text-align: center; margin-top: 50px;">
    <h1>Oops! You're Not Allowed To See This Page!<br>
      <a style="margin-top: 50px;" href="{% url 'appMarketplace:index' %}">GO HOME</a>
    </h1>
  </div>
{% endif %}


{% endblock %}

details/templates/details/job_details.html
{% extends 'details/base_details.html' %}

{% block title %}{{ job.title }}{% endblock %}

{% block body %}


<!--Job details-->
<div class="container">
  <div id="contact">
    <h1>{{ job.title }} - Details</h1>
    <h4><b>Description: </b>{{ job.short_text }}</h4>
    <h4><b>Job Duration: </b>{{ job.time }}</h4>
    <h4><b>Skills Needed: </b>{{ job.skill }}</h4>
    <h4><b>Budget: </b>{{ job.budget }}</h4>
    {% for u in user %}
      {% if u == job.user %}
        <h4><b>Job Posted By: </b><a href="{% url 'employee:profile' u.id %}">{{ job.user }}</a></h4>
      {% endif %}
    {% endfor %}
    <h4><b>Posted On: </b>{{ job.created_date }}</h4>

    {% if name.is_authenticated and name == job.user %}
      <a href="{% url 'details:edit_job' job.id %}" class="btn btn-primary" style="margin-bottom:5px;">Edit Job</a>
    {% endif %}
  </div>
</div>


<!--submit bid form-->
{% if name.is_authenticated and free_user == True and emp_user == False %}
  {% if bid_limit == False %}
    <div class="container">
      <form id="contact" method="POST" action="{% url 'details:job_details' job.id %}">
        {% csrf_token %}
        <h3>Submit Your Bid</h3>
        <fieldset>
          <textarea placeholder="Write Your Bid" name="bid_text" tabindex="1" required></textarea>
        </fieldset>
        <fieldset>
          <input placeholder="Time You Need (ex- 5 days)" name="bid_time" type="text" tabindex="2" required>
        </fieldset>
        <fieldset>
          <input placeholder="Budget You Need (ex- 100 dollars)" name="bid_budget" type="text" tabindex="3" required>
        </fieldset>
        <fieldset>
          <button name="submit" type="submit" id="contact-submit" data-submit="...Posting">Submit</button>
        </fieldset>
      </form>
    </div>
  {% endif %}
{% endif %}


<!--bid list-->
<div class="box-border">
  <h1 style="color: #F96; margin-bottom: -40px;">{{ count_bid }} Bids</h1>
  <section id="main">
    <article id="main-col">
      <ul>
        {% for bid in all_bids %}
          {% if job.id == bid.job.id %}
            <div class="card">
              <div class="card-body">
                <h2><a href="{% url 'freelancer:profile' bid.bid_poster.id %}">{{ bid.bid_poster }}</a></h2>
                <p><b>Bid Description:</b> {{ bid.bid_text }}</p>
                <p><b>Budget Needed: </b>{{ bid.bid_budget }}</p>
                <p><b>Time Needed:</b>  {{ bid.bid_time }}<p>

                {% if name == job.user %}
                  <a style="float: right;" href="{% url 'employee:e_home' %}" class="btn btn-primary" style="margin-bottom:5px;">Hire Me</a>
                {% endif %}
                {% if name.is_authenticated and name == bid.bid_poster %}
                  <a href="{% url 'details:edit_bid' bid.id %}" class="btn btn-primary" style="float:right;">Edit Bid</a>
                {% endif %}

                <p><b>Posted On:</b>  {{ bid.bid_posted_time }}<p>
              </div>
            </div>
          {% endif %}
        {% endfor %}
      </ul>
    </article>
  </section>
</div>





{% endblock %}